#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

generateDocument();

function generateDocument() {
  console.info('Generating index.js...');
  let document = `${executeFunction()}\n`;
  getFileNames().forEach(exercice => {
    document += `import {ex${exercice}} from './problems/${exercice}.js';\nrunExercice('ex${exercice}', ex${exercice});\n\n`;
  });

  fs.writeFileSync(path.join(__dirname, '..', '..', 'js', 'index.js'), document, { encoding: 'utf-8' });

  const { exec } = require('child_process');
  exec('git add **/index.js', (err) => {
    if (err) {
      console.error(err);
    } else {
      console.info('index.js generated successfully!');
    }
  });
}

function getFileNames() {
  return fs
    .readdirSync(path.join(__dirname, '..', '..', 'js', 'problems'))
    .map(f => +f.match(/\d+/)[0])
    .sort((a, b) => a - b);
}

function executeFunction() {
  return `function runExercice(label, fn) {\n\tconsole.time(label);\n\tconst exResult = fn();\n\tconsole.timeEnd(label);\n\tconsole.log(label, exResult);\n}\n\n`;
}